<div style="height: 50px; background: linear-gradient(to right, #e9d5ff, #a855f7, #6b21a8);"></div>

# Data Acquisition and Pre-Processing

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

from sklearn import metrics

import warnings
warnings.filterwarnings('ignore')

In [18]:
df = pd.read_excel("cardio_data_ml.xlsx", parse_dates=['date'])
display(df.head())

,date,country,id,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,occupation,smoke,weight,pca,disease
0,2021-05-03,Indonesia,0,1,5,0,110,80,1,2,1,168,Architect,0,62.0,0.9108,0
1,2021-08-05,Malaysia,1,1,5,0,140,90,3,1,1,156,Accountant,0,85.0,0.9380,1
2,2022-11-13,Indonesia,2,0,5,0,130,70,3,1,1,165,Chef,0,64.0,0.9190,1
3,2018-10-31,Singapore,3,1,4,0,150,100,1,2,1,169,Lawyer,0,82.0,0.7938,1
4,2020-09-25,Singapore,4,0,4,0,100,60,1,1,1,156,Architect,0,56.0,0.7346,0

In [3]:
df['height'] = df['height'].astype(float)

In [4]:
# overall information and data types of the columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         70000 non-null  datetime64[us]
 1   country      70000 non-null  str
 2   id           70000 non-null  int64
 3   active       70000 non-null  int64
 4   age_group    70000 non-null  int64
 5   alco         70000 non-null  int64
 6   ap_hi        70000 non-null  int64
 7   ap_lo        70000 non-null  int64
 8   cholesterol  70000 non-null  int64
 9   gender       70000 non-null  int64
 10  gluc         70000 non-null  int64
 11  height       70000 non-null  float64
 12  occupation   70000 non-null  str
 13  smoke        70000 non-null  int64
 14  weight       70000 non-null  float64
 15  pca          70000 non-null  float64
 16  disease      70000 non-null  int64
dtypes: datetime64[us](1), float64(3), int64(11), str(2)
memory usage: 10.0 MB

In [5]:
df.describe()

,date,id,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,smoke,weight,pca,disease
count,70000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,2020-07-01 10:51:11.314285,49972.419900,0.803729,4.855057,0.053771,126.848314,82.964514,1.366871,1.349571,1.226457,164.359229,0.088129,74.205690,0.905270,0.499700
min,2018-01-01 00:00:00,0.000000,0.000000,2.000000,0.000000,60.000000,40.000000,1.000000,1.000000,1.000000,55.000000,0.000000,10.000000,0.420800,0.000000
25%,2019-04-04 00:00:00,25006.750000,1.000000,4.000000,0.000000,120.000000,80.000000,1.000000,1.000000,1.000000,159.000000,0.000000,65.000000,0.780800,0.000000
50%,2020-06-30 00:00:00,50001.500000,1.000000,5.000000,0.000000,120.000000,80.000000,1.000000,1.000000,1.000000,165.000000,0.000000,72.000000,0.917800,0.000000
75%,2021-09-30 00:00:00,74889.250000,1.000000,5.000000,0.000000,140.000000,90.000000,2.000000,2.000000,1.000000,170.000000,0.000000,82.000000,0.951400,1.000000
max,2023-01-01 00:00:00,99999.000000,1.000000,6.000000,1.000000,200.000000,200.000000,3.000000,2.000000,3.000000,250.000000,1.000000,200.000000,1.257700,1.000000
std,NaN,28851.302323,0.397179,0.740231,0.225568,17.430948,16.824860,0.680250,0.476838,0.572270,8.210126,0.283484,14.395757,0.121503,0.500003

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

## Data Cleaning and Standardization

In [6]:
df.isnull().sum()

date           0
country        0
id             0
active         0
age_group      0
alco           0
ap_hi          0
ap_lo          0
cholesterol    0
gender         0
gluc           0
height         0
occupation     0
smoke          0
weight         0
pca            0
disease        0
dtype: int64

### Addressing missing, inaccurate, misleading information, data imputation methods

#### Imputation:
For missing data caused by outliers, imputation techniques such as mean, median, or interpolation can be used to replace outlier values with more representative values.

In [7]:
# Impute missing values (if any)
df['id'] = df['id'].bfill()
df['id'] = df['id'].ffill()
#df['id'].fillna(df['id'].mean(), inplace=True) # does not work
df.fillna({'id': df['id'].mean()},inplace=True) #work
df['id'] = df['id'].fillna(df['id'].mean())
display(df.head())

# Replace negative values in 'id' column with NaN
df['id'] = df['id'].apply(lambda x: np.nan if x < 0 else x)

# Interpolation for missing values
df['id'] = df['id'].interpolate(method='linear')

df.isnull().sum()

,date,country,id,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,occupation,smoke,weight,pca,disease
0,2021-05-03,Indonesia,0,1,5,0,110,80,1,2,1,168.0,Architect,0,62.0,0.9108,0
1,2021-08-05,Malaysia,1,1,5,0,140,90,3,1,1,156.0,Accountant,0,85.0,0.9380,1
2,2022-11-13,Indonesia,2,0,5,0,130,70,3,1,1,165.0,Chef,0,64.0,0.9190,1
3,2018-10-31,Singapore,3,1,4,0,150,100,1,2,1,169.0,Lawyer,0,82.0,0.7938,1
4,2020-09-25,Singapore,4,0,4,0,100,60,1,1,1,156.0,Architect,0,56.0,0.7346,0

date           0
country        0
id             0
active         0
age_group      0
alco           0
ap_hi          0
ap_lo          0
cholesterol    0
gender         0
gluc           0
height         0
occupation     0
smoke          0
weight         0
pca            0
disease        0
dtype: int64

In [9]:
# Check for duplicate records and drop them
data_dup = df[df.duplicated()]
display(data_dup)

df = df.drop_duplicates()

print("\nData after handling duplicate records:")
display(df.head())

Empty DataFrame
Columns: [date, country, id, active, age_group, alco, ap_hi, ap_lo, cholesterol, gender, gluc, height, occupation, smoke, weight, disease]
Index: []

Data after handling duplicate records:

,date,country,id,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,occupation,smoke,weight,disease
0,2021-05-03,Indonesia,0,1,5,0,110,80,1,2,1,168.0,Architect,0,62.0,0
1,2021-08-05,Malaysia,1,1,5,0,140,90,3,1,1,156.0,Accountant,0,85.0,1
2,2022-11-13,Indonesia,2,0,5,0,130,70,3,1,1,165.0,Chef,0,64.0,1
3,2018-10-31,Singapore,3,1,4,0,150,100,1,2,1,169.0,Lawyer,0,82.0,1
4,2020-09-25,Singapore,4,0,4,0,100,60,1,1,1,156.0,Architect,0,56.0,0

### Outlier Detection
**Outlier Detection (using zscore Data):**

In [8]:
from scipy import stats

# Calculate z-scores for outlier detection
z_scores = np.abs(stats.zscore(df['weight']))

# Set a threshold for z-score outliers (e.g., z-score > 2)
threshold = 2

# Identify outliers using z-score method
outliers_zscore = df[np.abs(z_scores) > threshold]

print("Data with outliers detected using z-score method:")
print(outliers_zscore)

Data with outliers detected using z-score method:
            date    country     id  active  age_group  alco  ap_hi  ap_lo  \
15    2018-01-08  Indonesia     24       0          4     0    120     80
23    2020-07-15  Singapore     33       1          6     0    110     60
30    2020-11-25      India     42       1          5     0    120     80
46    2018-12-17  Singapore     61       1          4     0    150     90
62    2022-06-26      India     81       1          5     1    130     90
...          ...        ...    ...     ...        ...   ...    ...    ...
69986 2021-08-01   Malaysia   3026       1          4     0    200    200
69989 2021-03-29      India  50521       1          5     0    200    200
69991 2020-09-28  Singapore  59301       1          5     0    200     40
69998 2020-02-15      India  94377       1          5     0    200    200
69999 2020-11-04      India  98095       1          4     0    200     40

       cholesterol  gender  gluc  height occupation  smoke  weight     pca  \
15               1       2     1   172.0   Engineer      0   112.0  0.7608
23               1       2     1   156.0     Doctor      0    45.0  1.0558
30               3       1     1   155.0    Teacher      0   105.0  0.9180
46               2       1     1   162.0     Doctor      0   107.0  0.7878
62               1       2     1   187.0       Chef      0   115.0  0.9988
...            ...     ...   ...     ...        ...    ...     ...     ...
69986            1       2     1   174.0       Chef      0   113.0  0.8888
69989            3       2     1   165.0     Others      1   105.0  1.0463
69991            1       1     1   154.0   Engineer      0    41.0  0.9496
69998            1       2     1   173.0     Others      0   112.0  1.0458
69999            1       1     1   156.0     Lawyer      0    41.0  0.7926

       disease
15           1
23           0
30           1
46           1
62           0
...        ...
69986        1
69989        1
69991        0
69998        1
69999        0

[3235 rows x 17 columns]

In [12]:
# Replace outliers with mean value
mean_value = df['height'].mean()
df_imputed = df.copy()

df_imputed.loc[abs(z_scores) > threshold, 'height'] = mean_value

print("Data after imputing outliers with mean value:")
print(df_imputed)

Data after imputing outliers with mean value:
            date    country     id  active  age_group  alco  ap_hi  ap_lo  \
0     2021-05-03  Indonesia      0       1          5     0    110     80
1     2021-08-05   Malaysia      1       1          5     0    140     90
2     2022-11-13  Indonesia      2       0          5     0    130     70
3     2018-10-31  Singapore      3       1          4     0    150    100
4     2020-09-25  Singapore      4       0          4     0    100     60
...          ...        ...    ...     ...        ...   ...    ...    ...
69995 2020-11-17      India  64340       1          4     0    200    200
69996 2020-05-09   Malaysia  84604       1          5     0    200    200
69997 2022-10-26      India  91461       1          5     0    200    200
69998 2020-02-15      India  94377       1          5     0    200    200
69999 2020-11-04      India  98095       1          4     0    200     40

       cholesterol  gender  gluc  height  occupation  smoke  weight  disease
0                1       2     1   168.0   Architect      0    62.0        0
1                3       1     1   156.0  Accountant      0    85.0        1
2                3       1     1   165.0        Chef      0    64.0        1
3                1       2     1   169.0      Lawyer      0    82.0        1
4                1       1     1   156.0   Architect      0    56.0        0
...            ...     ...   ...     ...         ...    ...     ...      ...
69995            1       1     2   152.0        Chef      0    85.0        1
69996            1       2     1   176.0      Others      0   100.0        1
69997            1       2     1   173.0    Engineer      1    85.0        1
69998            1       2     1   173.0      Others      0   112.0        1
69999            1       1     1   156.0      Lawyer      0    41.0        0

[70000 rows x 16 columns]

**IQR Method (Interquartile Range):**\
The IQR method identifies outliers based on the interquartile range, where values outside a specified range are considered outliers.

In [9]:
import pandas as pd

# Calculate quartiles and IQR
Q1 = df['disease'].quantile(0.25)
Q3 = df['disease'].quantile(0.75)
IQR = Q3 - Q1

# Identify outliers using IQR method
outliers_iqr = df[(df['disease'] < (Q1 - 1.5 * IQR)) | (df['disease'] > (Q3 + 1.5 * IQR))]

print("Data with outliers detected using IQR method:")
print(outliers_iqr)

Data with outliers detected using IQR method:
Empty DataFrame
Columns: [date, country, id, active, age_group, alco, ap_hi, ap_lo, cholesterol, gender, gluc, height, occupation, smoke, weight, pca, disease]
Index: []

**Outlier Management Isolation Forest:**

Let's use Python and `scikit-learn` library to demonstrate outlier management with sample data:

In [10]:
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest

dfx = df.copy()
dfx.drop(columns=['date', 'id', 'country', 'occupation'], inplace=True)

# Apply Isolation Forest for outlier detection
clf = IsolationForest(contamination=0.1, random_state=42)
outlier_labels = clf.fit_predict(dfx)

# Identify and remove outliers
df_cleaned = dfx[outlier_labels != -1]

# Display original and cleaned data
print("Original Data with Outliers:")
display(dfx)

print("\nCleaned Data without Outliers:")
display(df_cleaned)

Original Data with Outliers:

,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,smoke,weight,pca,disease
0,1,5,0,110,80,1,2,1,168.0,0,62.0,0.9108,0
1,1,5,0,140,90,3,1,1,156.0,0,85.0,0.9380,1
2,0,5,0,130,70,3,1,1,165.0,0,64.0,0.9190,1
3,1,4,0,150,100,1,2,1,169.0,0,82.0,0.7938,1
4,0,4,0,100,60,1,1,1,156.0,0,56.0,0.7346,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,1,4,0,200,200,1,1,2,152.0,0,85.0,0.8888,1
69996,1,5,0,200,200,1,2,1,176.0,0,100.0,1.0458,1
69997,1,5,0,200,200,1,2,1,173.0,1,85.0,1.0459,1
69998,1,5,0,200,200,1,2,1,173.0,0,112.0,1.0458,1
69999,1,4,0,200,40,1,1,1,156.0,0,41.0,0.7926,0

Cleaned Data without Outliers:

,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,smoke,weight,pca,disease
0,1,5,0,110,80,1,2,1,168.0,0,62.0,0.9108,0
1,1,5,0,140,90,3,1,1,156.0,0,85.0,0.9380,1
2,0,5,0,130,70,3,1,1,165.0,0,64.0,0.9190,1
3,1,4,0,150,100,1,2,1,169.0,0,82.0,0.7938,1
4,0,4,0,100,60,1,1,1,156.0,0,56.0,0.7346,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69988,1,4,0,200,40,1,1,1,170.0,0,64.0,0.7926,0
69990,1,5,0,200,40,1,1,1,162.0,0,50.0,0.9496,0
69991,1,5,0,200,40,1,1,1,154.0,0,41.0,0.9496,0
69993,1,4,0,200,40,1,2,1,176.0,0,69.0,0.7928,0
69999,1,4,0,200,40,1,1,1,156.0,0,41.0,0.7926,0

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

### MinMaxScaler Normalization (Standardization):
**Data Normalization**

In [11]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Initialize MinMaxScaler for normalization
scaler = MinMaxScaler()

# Normalize the data using Min-Max scaling
dfx = df.copy()
dfx.drop(columns=['date', 'id', 'country', 'occupation'], inplace=True)

df_normalized = pd.DataFrame(scaler.fit_transform(dfx), columns=dfx.columns) #df.columns

print("Original Data:")
display(dfx)

print("\nNormalized Data:")
display(df_normalized)

Original Data:

,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,smoke,weight,pca,disease
0,1,5,0,110,80,1,2,1,168.0,0,62.0,0.9108,0
1,1,5,0,140,90,3,1,1,156.0,0,85.0,0.9380,1
2,0,5,0,130,70,3,1,1,165.0,0,64.0,0.9190,1
3,1,4,0,150,100,1,2,1,169.0,0,82.0,0.7938,1
4,0,4,0,100,60,1,1,1,156.0,0,56.0,0.7346,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,1,4,0,200,200,1,1,2,152.0,0,85.0,0.8888,1
69996,1,5,0,200,200,1,2,1,176.0,0,100.0,1.0458,1
69997,1,5,0,200,200,1,2,1,173.0,1,85.0,1.0459,1
69998,1,5,0,200,200,1,2,1,173.0,0,112.0,1.0458,1
69999,1,4,0,200,40,1,1,1,156.0,0,41.0,0.7926,0

Normalized Data:

,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,smoke,weight,pca,disease
0,1.0,0.75,0.0,0.357143,0.2500,0.0,1.0,0.0,0.579487,0.0,0.273684,0.585494,0.0
1,1.0,0.75,0.0,0.571429,0.3125,1.0,0.0,0.0,0.517949,0.0,0.394737,0.617995,1.0
2,0.0,0.75,0.0,0.500000,0.1875,1.0,0.0,0.0,0.564103,0.0,0.284211,0.595292,1.0
3,1.0,0.50,0.0,0.642857,0.3750,0.0,1.0,0.0,0.584615,0.0,0.378947,0.445692,1.0
4,0.0,0.50,0.0,0.285714,0.1250,0.0,0.0,0.0,0.517949,0.0,0.242105,0.374955,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,1.0,0.50,0.0,1.000000,1.0000,0.0,0.0,0.5,0.497436,0.0,0.394737,0.559207,1.0
69996,1.0,0.75,0.0,1.000000,1.0000,0.0,1.0,0.0,0.620513,0.0,0.473684,0.746804,1.0
69997,1.0,0.75,0.0,1.000000,1.0000,0.0,1.0,0.0,0.605128,1.0,0.394737,0.746923,1.0
69998,1.0,0.75,0.0,1.000000,1.0000,0.0,1.0,0.0,0.605128,0.0,0.536842,0.746804,1.0
69999,1.0,0.50,0.0,1.000000,0.0000,0.0,0.0,0.0,0.517949,0.0,0.163158,0.444259,0.0

### Z-Score Normalization (Standardization):
**Z-Score Normalization:**

In [12]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Initialize StandardScaler for Z-score normalization
scaler_zscore = StandardScaler()

# Apply Z-score normalization to the data
dfx = df.copy()
dfx.drop(columns=['date', 'id', 'country', 'occupation'], inplace=True)

df_zscore_normalized = pd.DataFrame(scaler_zscore.fit_transform(dfx), columns=dfx.columns)

print("Original Data:")
display(dfx)

print("\nData after Z-score Normalization:")
display(df_zscore_normalized)

Original Data:

,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,smoke,weight,pca,disease
0,1,5,0,110,80,1,2,1,168.0,0,62.0,0.9108,0
1,1,5,0,140,90,3,1,1,156.0,0,85.0,0.9380,1
2,0,5,0,130,70,3,1,1,165.0,0,64.0,0.9190,1
3,1,4,0,150,100,1,2,1,169.0,0,82.0,0.7938,1
4,0,4,0,100,60,1,1,1,156.0,0,56.0,0.7346,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,1,4,0,200,200,1,1,2,152.0,0,85.0,0.8888,1
69996,1,5,0,200,200,1,2,1,176.0,0,100.0,1.0458,1
69997,1,5,0,200,200,1,2,1,173.0,1,85.0,1.0459,1
69998,1,5,0,200,200,1,2,1,173.0,0,112.0,1.0458,1
69999,1,4,0,200,40,1,1,1,156.0,0,41.0,0.7926,0

Data after Z-score Normalization:

,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,smoke,weight,pca,disease
0,0.494167,0.195809,-0.238384,-0.966582,-0.176200,-0.539322,1.364055,-0.395720,0.443452,-0.310879,-0.847873,0.045511,-0.9994
1,0.494167,0.195809,-0.238384,0.754507,0.418163,2.400793,-0.733108,-0.395720,-1.018168,-0.310879,0.749831,0.269375,1.0006
2,-2.023607,0.195809,-0.238384,0.180811,-0.770563,2.400793,-0.733108,-0.395720,0.078047,-0.310879,-0.708942,0.112999,1.0006
3,0.494167,-1.155130,-0.238384,1.328204,1.012526,-0.539322,1.364055,-0.395720,0.565254,-0.310879,0.541435,-0.917436,1.0006
4,-2.023607,-1.155130,-0.238384,-1.540278,-1.364925,-0.539322,-0.733108,-0.395720,-1.018168,-0.310879,-1.264666,-1.404671,-0.9994
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,0.494167,-1.155130,-0.238384,4.196686,6.956154,-0.539322,-0.733108,1.351719,-1.505375,-0.310879,0.749831,-0.135556,1.0006
69996,0.494167,0.195809,-0.238384,4.196686,6.956154,-0.539322,1.364055,-0.395720,1.417865,-0.310879,1.791812,1.156604,1.0006
69997,0.494167,0.195809,-0.238384,4.196686,6.956154,-0.539322,1.364055,-0.395720,1.052460,3.216684,0.749831,1.157427,1.0006
69998,0.494167,0.195809,-0.238384,4.196686,6.956154,-0.539322,1.364055,-0.395720,1.052460,-0.310879,2.625397,1.156604,1.0006
69999,0.494167,-1.155130,-0.238384,4.196686,-2.553651,-0.539322,-0.733108,-0.395720,-1.018168,-0.310879,-2.306647,-0.927313,-0.9994

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

### Explaination of encoding categorical variables for quantitative analysis, including one-hot encoding and label encoding methods

### 1. Label Encoding:
**Label Encoding:**

In [13]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder for label encoding
label_encoder = LabelEncoder()

# Apply label encoding to the 'Residential' column
df['age_group'] = label_encoder.fit_transform(df['age_group'])
df['cholesterol'] = label_encoder.fit_transform(df['cholesterol'])
df['gluc'] = label_encoder.fit_transform(df['gluc'])

print("\nData after Label Encoding:")
display(df[['age_group', 'cholesterol', 'gluc']])

Data after Label Encoding:

       age_group  cholesterol  gluc
0              3            0     0
1              3            2     0
2              3            2     0
3              2            0     0
4              2            0     0
...          ...          ...   ...
69995          2            0     1
69996          3            0     0
69997          3            0     0
69998          3            0     0
69999          2            0     0

[70000 rows x 3 columns]

### 2. One-Hot Encoding:
**Python Code for One-Hot Encoding:**

In [20]:
import pandas as pd

# Perform one-hot encoding using pandas' get_dummies function
#df_onehot = pd.get_dummies(df, columns=['occupation'], prefix='occupation')
df_onehot = pd.get_dummies(df)

print("Original Data:")
display(df[['country', 'occupation']])

print("\nData after One-Hot Encoding:")
display(df_onehot)

Original Data:

         country  occupation
0      Indonesia   Architect
1       Malaysia  Accountant
2      Indonesia        Chef
3      Singapore      Lawyer
4      Singapore   Architect
...          ...         ...
69995      India        Chef
69996   Malaysia      Others
69997      India    Engineer
69998      India      Others
69999      India      Lawyer

[70000 rows x 2 columns]

Data after One-Hot Encoding:

,date,id,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,...,country_Singapore,occupation_Accountant,occupation_Architect,occupation_Chef,occupation_Doctor,occupation_Engineer,occupation_Lawyer,occupation_Nurse,occupation_Others,occupation_Teacher
0,2021-05-03,0,1,5,0,110,80,1,2,1,...,False,False,True,False,False,False,False,False,False,False
1,2021-08-05,1,1,5,0,140,90,3,1,1,...,False,True,False,False,False,False,False,False,False,False
2,2022-11-13,2,0,5,0,130,70,3,1,1,...,False,False,False,True,False,False,False,False,False,False
3,2018-10-31,3,1,4,0,150,100,1,2,1,...,True,False,False,False,False,False,True,False,False,False
4,2020-09-25,4,0,4,0,100,60,1,1,1,...,True,False,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,2020-11-17,64340,1,4,0,200,200,1,1,2,...,False,False,False,True,False,False,False,False,False,False
69996,2020-05-09,84604,1,5,0,200,200,1,2,1,...,False,False,False,False,False,False,False,False,True,False
69997,2022-10-26,91461,1,5,0,200,200,1,2,1,...,False,False,False,False,False,True,False,False,False,False
69998,2020-02-15,94377,1,5,0,200,200,1,2,1,...,False,False,False,False,False,False,False,False,True,False
69999,2020-11-04,98095,1,4,0,200,40,1,1,1,...,False,False,False,False,False,False,True,False,False,False

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

### A simple data reduction technique using **Principal Component Analysis (PCA)**.

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         70000 non-null  datetime64[us]
 1   country      70000 non-null  str
 2   id           70000 non-null  int64
 3   active       70000 non-null  int64
 4   age_group    70000 non-null  int64
 5   alco         70000 non-null  int64
 6   ap_hi        70000 non-null  int64
 7   ap_lo        70000 non-null  int64
 8   cholesterol  70000 non-null  int64
 9   gender       70000 non-null  int64
 10  gluc         70000 non-null  int64
 11  height       70000 non-null  int64
 12  occupation   70000 non-null  str
 13  smoke        70000 non-null  int64
 14  weight       70000 non-null  float64
 15  pca          70000 non-null  float64
 16  disease      70000 non-null  int64
dtypes: datetime64[us](1), float64(2), int64(12), str(2)
memory usage: 10.0 MB

In [22]:
import pandas as pd
from sklearn.decomposition import PCA

# Initialize PCA with 12 components
pca = PCA(n_components=12)

df.drop(columns=['date', 'id', 'country', 'occupation'], inplace=True)

# Fit PCA to the data and transform it
df_reduced = pca.fit_transform(df)

print("Original Data:")
display(df)

print("\nData after PCA Data Reduction:")
print(df_reduced)
pca.explained_variance_ratio_.round(4)

Original Data:

,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,smoke,weight,pca,disease
0,1,5,0,110,80,1,2,1,168,0,62.0,0.9108,0
1,1,5,0,140,90,3,1,1,156,0,85.0,0.9380,1
2,0,5,0,130,70,3,1,1,165,0,64.0,0.9190,1
3,1,4,0,150,100,1,2,1,169,0,82.0,0.7938,1
4,0,4,0,100,60,1,1,1,156,0,56.0,0.7346,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,1,4,0,200,200,1,1,2,152,0,85.0,0.8888,1
69996,1,5,0,200,200,1,2,1,176,0,100.0,1.0458,1
69997,1,5,0,200,200,1,2,1,173,1,85.0,1.0459,1
69998,1,5,0,200,200,1,2,1,173,0,112.0,1.0458,1
69999,1,4,0,200,40,1,1,1,156,0,41.0,0.7926,0

Data after PCA Data Reduction:
[[-1.72258659e+01 -8.00091404e+00 -7.97256250e+00 ...  8.33398158e-02
  -3.07490835e-01  2.71087004e-02]
 [ 1.66885843e+01  4.47514436e+00  3.29789817e+00 ...  1.11611763e-01
  -5.43642555e-02 -3.22992426e-02]
 [-9.06111393e+00 -4.89215898e+00  1.28375609e+01 ... -8.07193303e-01
   2.36739870e-02 -1.52603351e-02]
 ...
 [ 1.30596090e+02 -3.32892432e+01 -3.13505004e+01 ...  9.68084506e-02
   5.14345181e-01 -4.95760862e-01]
 [ 1.38408791e+02 -8.81155268e+00 -3.61610287e+01 ...  1.06395654e-01
  -3.03696528e-01 -9.16862931e-03]
 [ 1.40167845e+01 -2.25723062e+01  8.73869151e+01 ...  1.04518909e-03
  -3.29934822e-02 -2.53265985e-03]]

array([5.479e-01, 2.249e-01, 1.570e-01, 6.800e-02, 7.000e-04, 6.000e-04,
       2.000e-04, 2.000e-04, 2.000e-04, 2.000e-04, 1.000e-04, 0.000e+00])

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

## Data Validation and Integrity

Validation rules are crucial for enforcing data correctness and consistency. Here's an example of applying clear validation rules using Python code:

In [23]:
import pandas as pd

# Define validation rules
active_rule = df['active'].isin([0, 1])

age_rule = (df['age_group'] >= 2) & (df['age_group'] <= 6)

alco_rule = df['alco'].isin([0, 1])

ap_hi_rule = (df['ap_hi'] >= 59) & (df['ap_hi'] <= 200)
ap_lo_rule = (df['ap_lo'] >= 40) & (df['ap_lo'] <= 200)

cholesterol_rule = df['cholesterol'].isin([1, 2, 3])

gender_rule = df['gender'].isin([1, 2])

gluc_rule = df['gluc'].isin([1, 2, 3])

smoke_rule = df['smoke'].isin([0, 1])
height_rule = (df['height'] >= 0) & (df['height'] <= 300)
weight_rule = (df['weight'] >= 0) & (df['weight'] <= 250)

disease_rule = df['disease'].isin([0, 1])

# Apply validation rules
valid_data = df[active_rule & age_rule & alco_rule & ap_hi_rule & ap_lo_rule & cholesterol_rule & gender_rule & gluc_rule & smoke_rule & height_rule & weight_rule & disease_rule]

# Display valid data after applying validation rules
print("Data after applying validation rules:")
display(valid_data)

Data after applying validation rules:

,active,age_group,alco,ap_hi,ap_lo,cholesterol,gender,gluc,height,smoke,weight,pca,disease
0,1,5,0,110,80,1,2,1,168,0,62.0,0.9108,0
1,1,5,0,140,90,3,1,1,156,0,85.0,0.9380,1
2,0,5,0,130,70,3,1,1,165,0,64.0,0.9190,1
3,1,4,0,150,100,1,2,1,169,0,82.0,0.7938,1
4,0,4,0,100,60,1,1,1,156,0,56.0,0.7346,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69995,1,4,0,200,200,1,1,2,152,0,85.0,0.8888,1
69996,1,5,0,200,200,1,2,1,176,0,100.0,1.0458,1
69997,1,5,0,200,200,1,2,1,173,1,85.0,1.0459,1
69998,1,5,0,200,200,1,2,1,173,0,112.0,1.0458,1
69999,1,4,0,200,40,1,1,1,156,0,41.0,0.7926,0

<div style="height: 50px; background: linear-gradient(to right, #e9d5ff, #a855f7, #6b21a8);"></div>