<div style="height: 50px; background: linear-gradient(to right, #e9d5ff, #a855f7, #6b21a8);"></div>

# SQL For Data Analysis

The SQL querying, CRUD operations, establishing database connections, parameterized queries, data type management, and security measures such as SQL injection prevention.

## Step 1: Setup

We will use sqlite3, execute the SQL operations in Jupyter Notebook.

### Importing required libraries:

In [1]:
import sqlite3
import pandas as pd

### Connecting to the SQLite database:

In [3]:
conn = sqlite3.connect('employee.db')
cursor = conn.cursor()

conn = sqlite3.connect('employee.db'): This line creates or connects to a SQLite database file called employee.db.

cursor = conn.cursor(): Allows to execute SQL commands and retrieve results from the database.

### Creating a table:

In [ ]:
cursor.execute('''CREATE TABLE IF NOT EXISTS employee (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    age INTEGER,
    department TEXT,
    salary REAL,
    hire_date TEXT,
    manager TEXT
)''')

### Employee data:

In [8]:
employees = [
    ('John Doe', 28, 'Sales', 50000.0, '2020-01-15', 'Jane Smith'),
    ('Emily Davis', 35, 'Marketing', 62000.0, '2018-11-23', 'Peter Johnson'),
    ('Michael Brown', 40, 'IT', 70000.0, '2016-03-10', 'Sam Wilson'),
    ('Sophia Green', 30, 'HR', 52000.0, '2021-05-21', 'Nina Lee'),
    ('James White', 42, 'Finance', 80000.0, '2015-09-07', 'Aaron Black'),
    ('Liam King', 32, 'Sales', 55000.0, '2019-02-19', 'Jane Smith'),
    ('Oliver Scott', 29, 'IT', 68000.0, '2020-08-29', 'Sam Wilson'),
    ('Amelia Lewis', 27, 'Marketing', 60000.0, '2020-04-17', 'Peter Johnson'),
    ('Mason Harris', 36, 'Sales', 65000.0, '2017-07-25', 'Jane Smith'),
    ('Isabella Clark', 33, 'Finance', 76000.0, '2016-10-30', 'Aaron Black'),
    ('Ethan Carter', 45, 'IT', 90000.0, '2012-06-15', 'Sam Wilson'),
    ('Mia Turner', 31, 'HR', 54000.0, '2021-11-09', 'Nina Lee'),
    ('Lucas Evans', 38, 'Finance', 78000.0, '2014-03-21', 'Aaron Black'),
    ('Harper Hill', 26, 'Marketing', 57000.0, '2021-09-12', 'Peter Johnson'),
    ('Alexander Baker', 37, 'Sales', 67000.0, '2018-05-19', 'Jane Smith'),
    ('Charlotte Young', 29, 'IT', 71000.0, '2019-10-11', 'Sam Wilson'),
    ('Benjamin Hall', 34, 'HR', 60000.0, '2020-03-01', 'Nina Lee'),
    ('Olivia Adams', 41, 'Finance', 83000.0, '2015-12-07', 'Aaron Black'),
    ('Sophia Foster', 28, 'Marketing', 61000.0, '2021-07-22', 'Peter Johnson'),
    ('Jackson Bell', 39, 'Sales', 69000.0, '2017-01-05', 'Jane Smith')
]

### Inserting data into the table:

In [10]:
cursor.executemany('''INSERT INTO employee (name, age, department, salary, hire_date, manager)
                      VALUES (?, ?, ?, ?, ?, ?)''', employees)
conn.commit()

cursor.executemany: This command executes the SQL INSERT statement for each tuple in the list.

conn.commit(): Commits the transaction to the database to ensure the changes (insertion of data) are saved.

### Verifying the data insertion:

In [12]:
pd.read_sql_query("SELECT * FROM employee", conn)

    id             name  age department   salary   hire_date        manager
0    1         John Doe   28      Sales  50000.0  2020-01-15     Jane Smith
1    2      Emily Davis   35  Marketing  62000.0  2018-11-23  Peter Johnson
2    3    Michael Brown   40         IT  70000.0  2016-03-10     Sam Wilson
3    4     Sophia Green   30         HR  52000.0  2021-05-21       Nina Lee
4    5      James White   42    Finance  80000.0  2015-09-07    Aaron Black
5    6        Liam King   32      Sales  55000.0  2019-02-19     Jane Smith
6    7     Oliver Scott   29         IT  68000.0  2020-08-29     Sam Wilson
7    8     Amelia Lewis   27  Marketing  60000.0  2020-04-17  Peter Johnson
8    9     Mason Harris   36      Sales  65000.0  2017-07-25     Jane Smith
9   10   Isabella Clark   33    Finance  76000.0  2016-10-30    Aaron Black
10  11     Ethan Carter   45         IT  90000.0  2012-06-15     Sam Wilson
11  12       Mia Turner   31         HR  54000.0  2021-11-09       Nina Lee
12  13      Lucas Evans   38    Finance  78000.0  2014-03-21    Aaron Black
13  14      Harper Hill   26  Marketing  57000.0  2021-09-12  Peter Johnson
14  15  Alexander Baker   37      Sales  67000.0  2018-05-19     Jane Smith
15  16  Charlotte Young   29         IT  71000.0  2019-10-11     Sam Wilson
16  17    Benjamin Hall   34         HR  60000.0  2020-03-01       Nina Lee
17  18     Olivia Adams   41    Finance  83000.0  2015-12-07    Aaron Black
18  19    Sophia Foster   28  Marketing  61000.0  2021-07-22  Peter Johnson
19  20     Jackson Bell   39      Sales  69000.0  2017-01-05     Jane Smith

### SQL query to extract data:

In [ ]:
df = pd.read_sql_query('''
    Select *
    from Table1
    inner join Table2
    on xx = xx
    inner join Table3
    on xx = xx
    ''', conn, index_col='id', parse_dates=['Date']))

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

## Step 2: Basic SQL Queries

### SELECT, FROM, and WHERE

In [14]:
# Select all employees from the 'Sales' department
query = '''SELECT * FROM employee WHERE department = "Sales"'''
pd.read_sql_query(query, conn)

   id             name  age department   salary   hire_date     manager
0   1         John Doe   28      Sales  50000.0  2020-01-15  Jane Smith
1   6        Liam King   32      Sales  55000.0  2019-02-19  Jane Smith
2   9     Mason Harris   36      Sales  65000.0  2017-07-25  Jane Smith
3  15  Alexander Baker   37      Sales  67000.0  2018-05-19  Jane Smith
4  20     Jackson Bell   39      Sales  69000.0  2017-01-05  Jane Smith

### JOINS (INNER, LEFT, RIGHT, FULL)

#### Create the Second Table

In [24]:
# Create the departments table
cursor.execute('''CREATE TABLE IF NOT EXISTS departments (
    department_name TEXT PRIMARY KEY,
    location TEXT
)''')

# Insert sample department data
departments = [
    ('Sales', 'New York'),
    ('Marketing', 'Los Angeles'),
    ('IT', 'San Francisco'),
    ('HR', 'Chicago'),
    ('Finance', 'Boston')
]

cursor.executemany('''INSERT INTO departments (department_name, location)
                      VALUES (?, ?)''', departments)
conn.commit()

#### If you get an error as : `UNIQUE constraint failed: departments.department_name` then execute the code below :

In [18]:
# Step 1: Delete all rows
cursor.execute('DELETE FROM departments')
conn.commit()

# Step 2: Drop and recreate the table
cursor.execute('DROP TABLE IF EXISTS departments')
conn.commit()

#### Inner Join

An inner join returns records that have matching values in both tables.

In [26]:
query_inner_join = '''
SELECT employee.name, employee.age, employee.salary, departments.location
FROM employee
INNER JOIN departments
ON employee.department = departments.department_name
'''

df_inner_join = pd.read_sql_query(query_inner_join, conn)
display("Inner Join:", df_inner_join)

'Inner Join:'

               name  age   salary       location
0          John Doe   28  50000.0       New York
1       Emily Davis   35  62000.0    Los Angeles
2     Michael Brown   40  70000.0  San Francisco
3      Sophia Green   30  52000.0        Chicago
4       James White   42  80000.0         Boston
5         Liam King   32  55000.0       New York
6      Oliver Scott   29  68000.0  San Francisco
7      Amelia Lewis   27  60000.0    Los Angeles
8      Mason Harris   36  65000.0       New York
9    Isabella Clark   33  76000.0         Boston
10     Ethan Carter   45  90000.0  San Francisco
11       Mia Turner   31  54000.0        Chicago
12      Lucas Evans   38  78000.0         Boston
13      Harper Hill   26  57000.0    Los Angeles
14  Alexander Baker   37  67000.0       New York
15  Charlotte Young   29  71000.0  San Francisco
16    Benjamin Hall   34  60000.0        Chicago
17     Olivia Adams   41  83000.0         Boston
18    Sophia Foster   28  61000.0    Los Angeles
19     Jackson Bell   39  69000.0       New York

#### Left Outer Join

A left outer join returns all records from the left table, and the matched records from the right table. \
If there is no match, NULL values are returned for columns from the right table.

In [29]:
query_left_outer_join = '''
SELECT employee.name, employee.age, employee.salary, departments.location
FROM employee
LEFT OUTER JOIN departments
ON employee.department = departments.department_name
'''

df_left_outer_join = pd.read_sql_query(query_left_outer_join, conn)
display("Left Outer Join:", df_left_outer_join)

'Left Outer Join:'

               name  age   salary       location
0          John Doe   28  50000.0       New York
1       Emily Davis   35  62000.0    Los Angeles
2     Michael Brown   40  70000.0  San Francisco
3      Sophia Green   30  52000.0        Chicago
4       James White   42  80000.0         Boston
5         Liam King   32  55000.0       New York
6      Oliver Scott   29  68000.0  San Francisco
7      Amelia Lewis   27  60000.0    Los Angeles
8      Mason Harris   36  65000.0       New York
9    Isabella Clark   33  76000.0         Boston
10     Ethan Carter   45  90000.0  San Francisco
11       Mia Turner   31  54000.0        Chicago
12      Lucas Evans   38  78000.0         Boston
13      Harper Hill   26  57000.0    Los Angeles
14  Alexander Baker   37  67000.0       New York
15  Charlotte Young   29  71000.0  San Francisco
16    Benjamin Hall   34  60000.0        Chicago
17     Olivia Adams   41  83000.0         Boston
18    Sophia Foster   28  61000.0    Los Angeles
19     Jackson Bell   39  69000.0       New York

#### Right Outer Join

**SQLite does not directly support right outer joins.** \
However, simulate a right outer join by swapping the table order in a left join and adjusting the query.

**SQLite version 3.39.0 and later supports RIGHT OUTER JOIN directly**

In [31]:
query_right_outer_join = '''
SELECT employee.name, employee.age, employee.salary, departments.location
FROM departments
LEFT OUTER JOIN employee
ON departments.department_name = employee.department
'''

df_right_outer_join = pd.read_sql_query(query_right_outer_join, conn)
display("Right Outer Join:", df_right_outer_join)

'Right Outer Join:'

               name  age   salary       location
0   Alexander Baker   37  67000.0       New York
1      Jackson Bell   39  69000.0       New York
2          John Doe   28  50000.0       New York
3         Liam King   32  55000.0       New York
4      Mason Harris   36  65000.0       New York
5      Amelia Lewis   27  60000.0    Los Angeles
6       Emily Davis   35  62000.0    Los Angeles
7       Harper Hill   26  57000.0    Los Angeles
8     Sophia Foster   28  61000.0    Los Angeles
9   Charlotte Young   29  71000.0  San Francisco
10     Ethan Carter   45  90000.0  San Francisco
11    Michael Brown   40  70000.0  San Francisco
12     Oliver Scott   29  68000.0  San Francisco
13    Benjamin Hall   34  60000.0        Chicago
14       Mia Turner   31  54000.0        Chicago
15     Sophia Green   30  52000.0        Chicago
16   Isabella Clark   33  76000.0         Boston
17      James White   42  80000.0         Boston
18      Lucas Evans   38  78000.0         Boston
19     Olivia Adams   41  83000.0         Boston

#### Full Outer Join

**SQLite does not directly support full outer joins.** \
Simulate a full outer join using a combination of left and right joins and a union operation.

**SQLite version 3.39.0 and later supports FULL OUTER JOIN directly**

In [33]:
query_full_outer_join = '''
SELECT employee.name, employee.age, employee.salary, departments.location
FROM employee
LEFT OUTER JOIN departments
ON employee.department = departments.department_name

UNION

SELECT employee.name, employee.age, employee.salary, departments.location
FROM departments
LEFT OUTER JOIN employee
ON departments.department_name = employee.department
'''

df_full_outer_join = pd.read_sql_query(query_full_outer_join, conn)
display("Full Outer Join:", df_full_outer_join)

'Full Outer Join:'

               name  age   salary       location
0   Alexander Baker   37  67000.0       New York
1      Amelia Lewis   27  60000.0    Los Angeles
2     Benjamin Hall   34  60000.0        Chicago
3   Charlotte Young   29  71000.0  San Francisco
4       Emily Davis   35  62000.0    Los Angeles
5      Ethan Carter   45  90000.0  San Francisco
6       Harper Hill   26  57000.0    Los Angeles
7    Isabella Clark   33  76000.0         Boston
8      Jackson Bell   39  69000.0       New York
9       James White   42  80000.0         Boston
10         John Doe   28  50000.0       New York
11        Liam King   32  55000.0       New York
12      Lucas Evans   38  78000.0         Boston
13     Mason Harris   36  65000.0       New York
14       Mia Turner   31  54000.0        Chicago
15    Michael Brown   40  70000.0  San Francisco
16     Oliver Scott   29  68000.0  San Francisco
17     Olivia Adams   41  83000.0         Boston
18    Sophia Foster   28  61000.0    Los Angeles
19     Sophia Green   30  52000.0        Chicago

In [ ]:
''' -- Full Outer Join on 4 Tables.
-- 1. Rows from TableA, including matches in B, C and D
SELECT
    COALESCE(a.id, b.id, c.id, d.id) AS id,
    a.value AS value_a,
    b.value AS value_b,
    c.value AS value_c,
    d.value AS value_d
FROM TableA a
LEFT JOIN TableB b ON a.id = b.id
LEFT JOIN TableC c ON COALESCE(a.id, b.id) = c.id
LEFT JOIN TableD d ON COALESCE(a.id, b.id, c.id) = d.id

UNION ALL

-- 2. Unmatched rows from TableB
SELECT
    COALESCE(a.id, b.id, c.id, d.id),
    a.value, b.value, c.value, d.value
FROM TableB b
LEFT JOIN TableA a ON b.id = a.id
LEFT JOIN TableC c ON b.id = c.id
LEFT JOIN TableD d ON COALESCE(b.id, c.id) = d.id
WHERE a.id IS NULL

UNION ALL

-- 3. Unmatched rows from TableC
SELECT
    COALESCE(a.id, b.id, c.id, d.id),
    a.value, b.value, c.value, d.value
FROM TableC c
LEFT JOIN TableA a ON c.id = a.id
LEFT JOIN TableB b ON c.id = b.id
LEFT JOIN TableD d ON c.id = d.id
WHERE a.id IS NULL AND b.id IS NULL

UNION ALL

-- 4. Unmatched rows from TableD
SELECT
    COALESCE(a.id, b.id, c.id, d.id),
    a.value, b.value, c.value, d.value
FROM TableD d
LEFT JOIN TableA a ON d.id = a.id
LEFT JOIN TableB b ON d.id = b.id
LEFT JOIN TableC c ON d.id = c.id
WHERE a.id IS NULL
  AND b.id IS NULL
  AND c.id IS NULL;
'''

'''
Part	Purpose
1	Returns all rows from TableA and matching rows from the other tables
2	Adds TableB rows that do not match TableA
3	Adds TableC rows that match neither TableA nor TableB
4	Adds TableD rows that match none of the first three tables
UNION ALL	Combines the results without removing duplicate rows
COALESCE()	Returns the first non-NULL ID
'''

### GROUP BY, HAVING, and ORDER BY

In [35]:
# Get the total salary by department, ordered by the total salary
query = '''
SELECT department, SUM(salary) AS total_salary
FROM employee
GROUP BY department
HAVING total_salary > 200000
ORDER BY total_salary DESC
'''
pd.read_sql_query(query, conn)

  department  total_salary
0    Finance      317000.0
1      Sales      306000.0
2         IT      299000.0
3  Marketing      240000.0

### LIMIT

In [37]:
# Select the first 5 employees with the highest salaries
query = '''SELECT * FROM employee ORDER BY salary DESC LIMIT 5'''
pd.read_sql_query(query, conn)

   id            name  age department   salary   hire_date      manager
0  11    Ethan Carter   45         IT  90000.0  2012-06-15   Sam Wilson
1  18    Olivia Adams   41    Finance  83000.0  2015-12-07  Aaron Black
2   5     James White   42    Finance  80000.0  2015-09-07  Aaron Black
3  13     Lucas Evans   38    Finance  78000.0  2014-03-21  Aaron Black
4  10  Isabella Clark   33    Finance  76000.0  2016-10-30  Aaron Black

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

## Step 3: CRUD Operations

### CREATE

In [49]:
cursor.execute('''
CREATE TABLE IF NOT EXISTS sales (
    order_id INTEGER PRIMARY KEY,
    product_name TEXT,
    quantity INTEGER,
    price REAL,
    order_date TEXT
)
''')
conn.commit()

df = pd.read_sql_query('''
SELECT * FROM sales
''', conn)
display(df)

Empty DataFrame
Columns: [order_id, product_name, quantity, price, order_date]
Index: []

### INSERT

Inserting was shown earlier when populating the employee table.

In [51]:
sales_data = [
    (1, 'Laptop', 2, 1200.00, '2024-09-01'),
    (2, 'Smartphone', 5, 800.00, '2024-09-02'),
    (3, 'Headphones', 10, 150.00, '2024-09-03'),
    (4, 'Monitor', 3, 300.00, '2024-09-04'),
    (5, 'Keyboard', 7, 50.00, '2024-09-05'),
    (6, 'Mouse', 8, 25.00, '2024-09-06'),
    (7, 'Printer', 4, 150.00, '2024-09-07'),
    (8, 'Webcam', 6, 75.00, '2024-09-08'),
    (9, 'Desk Chair', 2, 200.00, '2024-09-09'),
    (10, 'Desk Lamp', 9, 30.00, '2024-09-10')
]
cursor.executemany('''
INSERT INTO sales (order_id, product_name, quantity, price, order_date) VALUES (?, ?, ?, ?, ?)
''', sales_data)
conn.commit()

df = pd.read_sql_query('''
SELECT * FROM sales
''', conn)
display(df)

   order_id product_name  quantity   price  order_date
0         1       Laptop         2  1200.0  2024-09-01
1         2   Smartphone         5   800.0  2024-09-02
2         3   Headphones        10   150.0  2024-09-03
3         4      Monitor         3   300.0  2024-09-04
4         5     Keyboard         7    50.0  2024-09-05
5         6        Mouse         8    25.0  2024-09-06
6         7      Printer         4   150.0  2024-09-07
7         8       Webcam         6    75.0  2024-09-08
8         9   Desk Chair         2   200.0  2024-09-09
9        10    Desk Lamp         9    30.0  2024-09-10

#### If you get an error as : `UNIQUE constraint failed: sales.order_id` only then execute the code below :

In [43]:
# Step 1: Delete all rows
cursor.execute('DELETE FROM sales')
conn.commit()

# Step 2: Drop and recreate the table
cursor.execute('DROP TABLE IF EXISTS sales')
conn.commit()

### UPDATE

In [53]:
cursor.execute('''
UPDATE sales
SET quantity = 10
WHERE order_id = 4
''')
conn.commit()

### RETRIEVE

In [55]:
df = pd.read_sql_query('''
SELECT * FROM sales
''', conn)
display(df)

   order_id product_name  quantity   price  order_date
0         1       Laptop         2  1200.0  2024-09-01
1         2   Smartphone         5   800.0  2024-09-02
2         3   Headphones        10   150.0  2024-09-03
3         4      Monitor        10   300.0  2024-09-04
4         5     Keyboard         7    50.0  2024-09-05
5         6        Mouse         8    25.0  2024-09-06
6         7      Printer         4   150.0  2024-09-07
7         8       Webcam         6    75.0  2024-09-08
8         9   Desk Chair         2   200.0  2024-09-09
9        10    Desk Lamp         9    30.0  2024-09-10

### DELETE

In [57]:
cursor.execute('''
DELETE FROM sales
WHERE order_id = 10
''')
conn.commit()

df = pd.read_sql_query('''
SELECT * FROM sales
''', conn)
display(df)

   order_id product_name  quantity   price  order_date
0         1       Laptop         2  1200.0  2024-09-01
1         2   Smartphone         5   800.0  2024-09-02
2         3   Headphones        10   150.0  2024-09-03
3         4      Monitor        10   300.0  2024-09-04
4         5     Keyboard         7    50.0  2024-09-05
5         6        Mouse         8    25.0  2024-09-06
6         7      Printer         4   150.0  2024-09-07
7         8       Webcam         6    75.0  2024-09-08
8         9   Desk Chair         2   200.0  2024-09-09

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

## Step 4: Database Connections Using Python

Here are the steps for connecting to a database using Python:

1. **Import the Database Library**: Start by importing the appropriate library for the database you are using `sqlite3` for SQLite 

`import sqlite3`


2. **Create a Connection**: Establish a connection to the database using the library's connection function. For SQLite, you connect to a database file. 

`conn = sqlite3.connect('database.db')` 

3. **Create a Cursor Object**: Create a cursor object from the connection. The cursor is used to execute SQL commands and interact with the database

`cursor = conn.cursor()`

4. **Execute SQL Commands**: Use the cursor to execute SQL commands, such as creating tables, inserting data, or querying the database

`cursor.execute('SQL COMMAND')`

5. **Commit Changes**: If you make any changes to the database (like inserting or updating data), commit these changes 

`conn.commit()`

6. **Retrieve Data**: Execute queries to retrieve data from the database. Use methods provided by the cursor to fetch and proc

`cursor.execute('SELECT * FROM table_name')
rows = cursor.fetchall(`)

7. **Close the Connection**: Finally, close the connection to the database to free up resources and ensure that all transactions are

`conn.close()`
 properly completed.operly completed.perly completed.

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

## Step 5: Parameterized SQL Queries

In [59]:
# Using parameterized queries to prevent SQL injection
def get_employee_by_department(dept):
    query = '''SELECT * FROM employee WHERE department = ?'''
    return pd.read_sql_query(query, conn, params=(dept,))

# Example usage
get_employee_by_department("IT")

   id             name  age department   salary   hire_date     manager
0   3    Michael Brown   40         IT  70000.0  2016-03-10  Sam Wilson
1   7     Oliver Scott   29         IT  68000.0  2020-08-29  Sam Wilson
2  11     Ethan Carter   45         IT  90000.0  2012-06-15  Sam Wilson
3  16  Charlotte Young   29         IT  71000.0  2019-10-11  Sam Wilson

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

## Step 6: SQL Data Types in Python

When interacting with databases, it’s crucial to handle SQL and Python data types correctly.

In [61]:
# Example of converting SQL data types to Python types
df = pd.read_sql_query("SELECT * FROM employee", conn)

# Converting 'salary' to integer (if needed)
df['salary'] = df['salary'].astype(int)

df.dtypes  # Display the data types of the DataFrame

id             int64
name          object
age            int64
department    object
salary         int32
hire_date     object
manager       object
dtype: object

The code retrieves data from the `employee` table into a Pandas DataFrame, converts the `salary` column to integers, and then displays the DataFrame's data types.

<div style="height: 50px; background: linear-gradient(to right, lightblue, blue, darkblue);"></div>

## Step 7: Database Security

Preventing SQL injection through parameterized queries has already been demonstrated.

A key security concept: Avoid using raw SQL queries with user input directly.

In [ ]:
# Bad practice (vulnerable to SQL injection)
def bad_get_employee_by_name(name):
    query = f"SELECT * FROM employee WHERE name = '{name}'"
    return pd.read_sql_query(query, conn)

# Good practice (parameterized queries)
def secure_get_employee_by_name(name):
    query = "SELECT * FROM employee WHERE name = ?"
    return pd.read_sql_query(query, conn, params=(name,))

# Example of secure query
secure_get_employee_by_name("Sophia Green")

The code demonstrates two methods for querying a database to retrieve employee data by name. 

The `bad_get_employee_by_name` function illustrates a vulnerable approach prone to SQL injection attacks, as it directly incorporates the `name` variable into the SQL query string, allowing malicious inputs to manipulate or damage the database (e.g., deleting the table). 

In contrast, the `secure_get_employee_by_name` function employs parameterized queries, a safer practice that prevents SQL injection by using placeholders (`?`) for parameters and passing the actual values separately. This method ensures that user inputs are treated as data rather than executable code, protecting the database from such vulnerabilities.

<div style="height: 50px; background: linear-gradient(to right, #e9d5ff, #a855f7, #6b21a8);"></div>